### ISSUE TITLE
能否考虑增加一个出链和入链的查询接口

### ISSUE THREAD

**Issue by peng1999** [zxhd863943427/siyuan-plugin-data-query#1]
例如：
- `async dv.pageOutlinks(block | id) : block[]`
- `async dv.pageBacklinks(block | id) : block[]`

分别构造SQL
- `SELECT def_block_id FROM refs WHERE root_id = ?`
- `SELECT block_id FROM refs WHERE def_block_root_id = ?`

查询某个页面的的出链和入链

**Comment by zxhd863943427** [comment]
不错的提议，我回头试试看。

**Comment by zxhd863943427** [comment]
已经实现了，原型如下：
```
outlinks(blockArg:string|string[]|DataViewBlock|DataViewBlock[]|undefined)
backlinks(blockArg:string|string[]|DataViewBlock|DataViewBlock[]|undefined)
```
有时间可以帮忙写下文档，懒癌发作不想写了
